FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD redbus.jar /opt/redbus/
EXPOSE 8080
WORKDIR /opt/redbus/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "redbus.jar"]
